CREATE TABLE IF NOT EXISTS housekeeping_status (
  id INT AUTO_INCREMENT PRIMARY KEY,
  housekeeper_name VARCHAR(120) NOT NULL,
  customer_rating DECIMAL(2,1) NOT NULL,
  hours_start TIME NOT NULL,
  hours_end TIME NOT NULL,
  availability_status VARCHAR(20) NOT NULL,
  assigned_room VARCHAR(30),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
