CREATE TABLE IF NOT EXISTS room_rates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room_type VARCHAR(60) NOT NULL,
  season VARCHAR(60) NOT NULL,
  nightly_rate DECIMAL(10,2) NOT NULL,
  package_name VARCHAR(120),
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
