package com.oceanviewresort.controller;

import com.oceanviewresort.model.Report;
import com.oceanviewresort.model.ReportDao;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

@Controller
@RequestMapping("/reports")
public class ReportsController {
    private final ReportDao reportDao;

    public ReportsController(ReportDao reportDao) {
        this.reportDao = reportDao;
    }

    @GetMapping({"", "/"})
    public String reportsPage(@RequestParam(value = "editId", required = false) Integer editId,
                              Model model,
                              HttpServletRequest request,
                              HttpServletResponse response) throws IOException {
        if (!ensureAdmin(request, response)) {
            return null;
        }

        Report form = new Report();
        if (editId != null) {
            Report existing = reportDao.findById(editId);
            if (existing != null) {
                form = existing;
            } else {
                model.addAttribute("errorMessage", "Selected report was not found.");
            }
        }

        model.addAttribute("reportForm", form);
        model.addAttribute("reportList", reportDao.findAll());
        return "reports";
    }

    @PostMapping("/save")
    public String saveReport(Report report,
                             Model model,
                             HttpServletRequest request,
                             HttpServletResponse response) throws IOException {
        if (!ensureAdmin(request, response)) {
            return null;
        }

        List<String> errors = validate(report);
        if (!errors.isEmpty()) {
            model.addAttribute("reportForm", report);
            model.addAttribute("reportList", reportDao.findAll());
            model.addAttribute("errorMessage", String.join(" ", errors));
            return "reports";
        }

        if (report.getId() == null) {
            reportDao.create(report);
        } else {
            reportDao.update(report);
        }
        return "redirect:/reports";
    }

    @PostMapping("/delete")
    public String deleteReport(@RequestParam("id") int id,
                               HttpServletRequest request,
                               HttpServletResponse response) throws IOException {
        if (!ensureAdmin(request, response)) {
            return null;
        }
        reportDao.delete(id);
        return "redirect:/reports";
    }

    private boolean ensureAdmin(HttpServletRequest request, HttpServletResponse response) throws IOException {
        HttpSession session = request.getSession(false);
        String username = session == null ? null : (String) session.getAttribute("username");
        if (username == null) {
            response.sendRedirect(request.getContextPath() + "/login?error=1");
            return false;
        }
        if (!"admin".equalsIgnoreCase(username)) {
            response.sendError(HttpServletResponse.SC_FORBIDDEN, "Access denied");
            return false;
        }
        return true;
    }

    private List<String> validate(Report report) {
        List<String> errors = new ArrayList<>();
        if (isBlank(report.getReportName())) {
            errors.add("Report name is required.");
        }
        if (isBlank(report.getReportType())) {
            errors.add("Report type is required.");
        }
        if (isBlank(report.getPeriodStart()) || isBlank(report.getPeriodEnd())) {
            errors.add("Report period start and end are required.");
        }
        if (isBlank(report.getStatus())) {
            errors.add("Status is required.");
        }
        if (isBlank(report.getGeneratedBy())) {
            errors.add("Generated by is required.");
        }
        return errors;
    }

    private boolean isBlank(String value) {
        return value == null || value.trim().isEmpty();
    }
}
